import type { FeatureLayerProps } from '../../types';
import type EsriFeatureLayer from '@arcgis/core/layers/FeatureLayer';
import { useEsriModule } from '../../hooks/useEsriModule';
import { useLayer } from '../../hooks/useLayer';
import { usePropertyUpdater } from '../../hooks/usePropertyUpdater';

export function FeatureLayer({
  apiKey,
  attributeTableTemplate,
  blendMode,
  copyright,
  customParameters,
  dateFieldsTimeZone,
  definitionExpression,
  displayField,
  displayFilterEnabled,
  displayFilterInfo,
  dynamicDataSource,
  effect,
  elevationInfo,
  featureEffect,
  featureReduction,
  fieldConfigurations,
  fields,
  floorInfo,
  formTemplate,
  gdbVersion,
  geometryType,
  globalIdField,
  hasM,
  hasZ,
  historicMoment,
  id,
  labelingInfo,
  labelsVisible,
  layerId,
  legendEnabled,
  listMode,
  maxScale,
  minScale,
  objectIdField,
  orderBy,
  outFields = ['*'],
  persistenceEnabled,
  popupEnabled,
  popupTemplate,
  portalItem,
  refreshInterval,
  renderer,
  returnM,
  returnZ,
  screenSizePerspectiveEnabled,
  source,
  timeExtent,
  timeInfo,
  timeOffset,
  title,
  trackInfo,
  typeIdField,
  types,
  url,
  useViewTime,
  visibilityTimeExtent,
  visible = true,
  opacity = 1,
  map,
  view,
  onLoad
}: FeatureLayerProps) {
  const { Module } = useEsriModule<EsriFeatureLayer>(
    () => import('@arcgis/core/layers/FeatureLayer'),
    'FeatureLayer'
  );

  const layer = useLayer({
    Module,
    config: {
      apiKey,
      attributeTableTemplate,
      blendMode,
      copyright,
      customParameters,
      dateFieldsTimeZone,
      definitionExpression,
      displayField,
      displayFilterEnabled,
      displayFilterInfo,
      dynamicDataSource,
      effect,
      elevationInfo,
      featureEffect,
      featureReduction,
      fieldConfigurations,
      fields,
      floorInfo,
      formTemplate,
      gdbVersion,
      geometryType,
      globalIdField,
      hasM,
      hasZ,
      historicMoment,
      id,
      labelingInfo,
      labelsVisible,
      layerId,
      legendEnabled,
      listMode,
      maxScale,
      minScale,
      objectIdField,
      orderBy,
      outFields,
      persistenceEnabled,
      popupEnabled,
      popupTemplate,
      portalItem,
      refreshInterval,
      renderer,
      returnM,
      returnZ,
      screenSizePerspectiveEnabled,
      source,
      timeExtent,
      timeInfo,
      timeOffset,
      title,
      trackInfo,
      typeIdField,
      types,
      url,
      useViewTime,
      visibilityTimeExtent,
      visible,
      opacity
    },
    map,
    onLoad
  });

  usePropertyUpdater(layer, {
    blendMode: { value: blendMode },
    copyright: { value: copyright, condition: copyright !== undefined },
    definitionExpression: { value: definitionExpression, condition: definitionExpression !== undefined },
    displayField: { value: displayField, condition: displayField !== undefined },
    displayFilterEnabled: { value: displayFilterEnabled },
    effect: { value: effect as __esri.Effect | null, condition: effect !== undefined },
    featureEffect: { value: featureEffect as __esri.FeatureEffect | null, condition: featureEffect !== undefined },
    gdbVersion: { value: gdbVersion, condition: gdbVersion !== undefined },
    historicMoment: { value: historicMoment as Date | null, condition: historicMoment !== undefined },
    labelsVisible: { value: labelsVisible },
    legendEnabled: { value: legendEnabled },
    listMode: { value: listMode },
    maxScale: { value: maxScale },
    minScale: { value: minScale },
    orderBy: { value: orderBy as __esri.OrderByInfo[] | null, condition: orderBy !== undefined },
    outFields: { value: outFields, condition: outFields !== undefined },
    persistenceEnabled: { value: persistenceEnabled },
    popupEnabled: { value: popupEnabled },
    popupTemplate: { value: popupTemplate as __esri.PopupTemplate | null, condition: popupTemplate !== undefined },
    refreshInterval: { value: refreshInterval, condition: refreshInterval !== undefined },
    renderer: { value: renderer as __esri.RendererUnion | null, condition: renderer !== undefined },
    returnM: { value: returnM, condition: returnM !== undefined },
    returnZ: { value: returnZ, condition: returnZ !== undefined },
    screenSizePerspectiveEnabled: { value: screenSizePerspectiveEnabled },
    timeExtent: { value: timeExtent as __esri.TimeExtent | null, condition: timeExtent !== undefined },
    timeOffset: { value: timeOffset as __esri.TimeInterval | null, condition: timeOffset !== undefined },
    title: { value: title },
    useViewTime: { value: useViewTime },
    visibilityTimeExtent: { value: visibilityTimeExtent as __esri.TimeExtent | null, condition: visibilityTimeExtent !== undefined },
    visible: { value: visible },
    opacity: { value: opacity }
  });

  return null;
}

export default FeatureLayer;
